name: build

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master
      - develop
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
        lazarus-versions: [dist, 2.0.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.1
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1",
        "JPLib",
        "JPPack",
        "BGRABitmap",
        "BGRAControls",
        "MORMot",
        "HashLib",
        "UniqueInstance",
        "VirtualTreeView V5",
        "LCLExtensions",
        "KControls"
    - name: Build the ASuite Components
      run: lazbuild "3p/ASuiteComps.lpk"
    - name: Build the Main Application
      run: lazbuild "ASuite.lpi"